[package]
name = "maid_distribution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.31.0"
minreq = { version = "2.11.0", features = ["https-rustls"] }
sha256 = "1.4.0"
